/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multisnake;

import java.awt.Font;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.NotBoundException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;

public class App {

    public static void main(String[] args) throws RemoteException, MalformedURLException, NotBoundException {
		IServer server = (IServer) Naming.lookup("rmi://127.0.0.1:1098/ServerCallback");
		IClient client = new Client(server);
		System.out.println("RMI Callback Client Started");
    }

}
